name: weather_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  async: ^2.0.8
  get_it: ^3.0.0+1
  provider: ^4.3.1
  provider_architecture: ^1.0.3
  firebase_auth: ^0.15.3
  cloud_firestore: ^0.13.0+1
  validators: ^2.0.0+1
  timeago: ^2.0.26
  shared_preferences: ^0.5.3+4
  jiffy: ^3.0.1
  geocoding: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
